import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Page.module.css'
 

const Page: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <main className={styles.main}>
       page
      </main>
      
    </div>
  )
}

export default Page
